---
settings:
  name: Astra Trident
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Astra Trident
    url: "/trident-2204"
    version-number: '22.04'
  - name: Astra Trident
    url: "/trident"
    version-number: '23.07'
  - name: Astra Trident
    url: "/trident-2201"
    version-number: '22.01'
  - name: Astra Trident
    url: "/trident-2110"
    version-number: '21.10'
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione di Astra Trident
    url: "/index.html"
  - title: Note di rilascio
    url: "/trident-rn.html"
  - section: trident-concepts
  - section: trident-get-started
  - section: trident-managing-k8s
  - section: trident-use
  - section: trident-docker
  - title: FAQ
    url: "/faq.html"
  - title: Supporto
    url: "/get-help.html"
  - title: Risoluzione dei problemi
    url: "/troubleshooting.html"
  - section: trident-reco
  - section: trident-reference
  - title: Versioni precedenti
    url: "/earlier-versions.html"
  - title: Note legali
    url: "/legal.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: trident-rn.html
    - title: Introduzione ad Astra Trident
      url: "/trident-concepts/intro.html"
    - title: Requisiti di Astra Trident
      url: "/trident-get-started/requirements.html"
    - title: Provalo
      url: "/trident-get-started/quickstart.html"
    - title: FAQ
      url: "/faq.html"
  - title: Implementare Astra Trident
    links:
    - title: Implementazione con l'operatore Trident
      url: "/trident-get-started/kubernetes-deploy-operator.html"
    - title: Implementare con tridentctl
      url: "/trident-get-started/kubernetes-deploy-tridentctl.html"
    - title: Implementa Astra Trident per Docker
      url: "/trident-docker/deploy-docker.html"
  - title: Aggiorna Astra Trident
    links:
    - title: Aggiorna con l'operatore Trident
      url: "/trident-managing-k8s/upgrade-operator.html"
    - title: Upgrade con tridentctl
      url: "/trident-managing-k8s/upgrade-tridentctl.html"
  - title: Utilizzare Astra Trident
    links:
    - title: Configurare i backend
      url: "/trident-use/backends.html"
    - title: Crea backend con kubectl
      url: "/trident-use/backend-kubectl.html"
    - title: Passare da un'opzione di gestione back-end all'altra
      url: "/trident-use/backend_options.html"
    - title: Gestire le classi di storage
      url: "/trident-use/manage-stor-class.html"
    - title: Eseguire operazioni sui volumi
      url: "/trident-use/vol-operations.html"
    - title: Monitorare Astra Trident
      url: "/trident-use/monitor-trident.html"
  - title: Demo e tutorial
    links:
    - title: Video di Astra Trident
      url: https://tv.netapp.com/detail/video/5995831475001/using-trident-with-kubernetes
  - title: Blog e community
    links:
    - title: Blog di Astra
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Blog di Astra Trident
      url: https://netapp.io/persistent-storage-provisioner-for-kubernetes/
    - title: Hub Kubernetes
      url: https://cloud.netapp.com/kubernetes-hub
    - title: NetApp.io
      url: https://netapp.io/
    - title: Lasco
      url: https://netapppub.slack.com/
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Tutta la documentazione Astra
