---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx 
summary: Inizia esaminando i frontend, i backend e la configurazione host supportati. 
---
= Requisiti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Inizia esaminando i frontend, i backend e la configurazione host supportati.


NOTE: Per ulteriori informazioni sulle porte utilizzate da Astra Trident, vedere link:../trident-reference/trident-ports.html["qui"^].



== Frontend supportati (orchestratori)

Astra Trident supporta diversi motori e orchestratori di container, tra cui:

* Anthos on-Prem (VMware) e anthos on Bare Metal 1.9, 1.10, 1.11
* Kubernetes 1.18 - 1.24
* Motore di Mirantis Kubernetes 3.4
* OpenShift 4.7, 4.8, 4.9, 4.10


L'operatore Trident è supportato con le seguenti versioni:

* Anthos on-Prem (VMware) e anthos on Bare Metal 1.9, 1.10, 1.11
* Kubernetes 1.18 - 1.24
* OpenShift 4.7, 4.8, 4.9, 4.10


Astra Trident lavora anche con una serie di altre offerte Kubernetes completamente gestite e autogestite, tra cui Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Rancher e VMware Tanzu Portfolio.



== Back-end supportati (storage)

Per utilizzare Astra Trident, sono necessari uno o più dei seguenti backend supportati:

* Amazon FSX per NetApp ONTAP
* Azure NetApp Files
* Archivio dati Astra
* Cloud Volumes ONTAP
* Cloud Volumes Service per GCP
* FAS/AFF/Select 9.3 o versione successiva
* Array All SAN (ASA) NetApp
* Software NetApp HCI/Element 11 o versione successiva




== Requisiti delle funzionalità

La tabella seguente riassume le funzionalità disponibili con questa release di Astra Trident e le versioni di Kubernetes supportate.

[cols="3"]
|===
| Funzione | Versione di Kubernetes | Sono richiesti i gate delle funzionalità? 


| Trident CSI  a| 
1.18 - 1.24
 a| 
No



| Snapshot dei volumi  a| 
1.18 - 1.24
 a| 
No



| PVC dalle istantanee dei volumi  a| 
1.18 - 1.24
 a| 
No



| Ridimensionamento di iSCSI PV  a| 
1.18 - 1.24
 a| 
No



| CHAP bidirezionale ONTAP  a| 
1.18 - 1.24
 a| 
No



| Policy di esportazione dinamiche  a| 
1.18 - 1.24
 a| 
No



| Operatore Trident  a| 
1.18 - 1.24
 a| 
No



| Preparazione automatica dei nodi di lavoro (beta)  a| 
1.18 - 1.24
 a| 
No



| Topologia CSI  a| 
1.18 - 1.24
 a| 
No

|===


== Sistemi operativi host testati

Per impostazione predefinita, Astra Trident viene eseguito in un container e, di conseguenza, viene eseguito su qualsiasi worker Linux. Tuttavia, questi lavoratori devono essere in grado di montare i volumi forniti da Astra Trident utilizzando il client NFS standard o iSCSI Initiator, a seconda dei backend utilizzati.

Sebbene Astra Trident non supporti ufficialmente sistemi operativi specifici, le seguenti distribuzioni Linux sono note per funzionare:

* Versioni di RedHat CoreOS (RHCOS) supportate da OpenShift Container Platform
* RHEL o CentOS 7.4 o versione successiva
* Ubuntu 18.04 o versione successiva


Il `tridentctl` Utility può essere eseguita anche su una qualsiasi di queste distribuzioni di Linux.



== Configurazione dell'host

A seconda del backend in uso, le utility NFS e/o iSCSI devono essere installate su tutti gli utenti del cluster. Vedere link:../trident-use/worker-node-prep.html["qui"^] per ulteriori informazioni.



== Configurazione del sistema storage

Astra Trident potrebbe richiedere alcune modifiche a un sistema storage prima che possa essere utilizzato da una configurazione di back-end. Vedere link:../trident-use/backends.html["qui"^] per ulteriori informazioni.



== Immagini container e corrispondenti versioni di Kubernetes

Per le installazioni a gapping d'aria, l'elenco seguente è un riferimento alle immagini dei container necessarie per installare Astra Trident. Utilizzare `tridentctl images` per verificare l'elenco delle immagini container necessarie.

[cols="2"]
|===
| Versione di Kubernetes | Immagine container 


| v1.18.0  a| 
* netapp/tridente:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (opzionale)




| v1.19.0  a| 
* netapp/tridente:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (opzionale)




| v1.20.0  a| 
* netapp/tridente:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (opzionale)




| v1.21.1.0  a| 
* netapp/tridente:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (opzionale)




| v1.22.0  a| 
* netapp/tridente:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (opzionale)




| v1.23.0  a| 
* netapp/tridente:22.04.0
* netapp/trident-autosupport:22.04
* k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
* k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
* k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
* k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
* k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
* netapp/trident-operator:22.04.0 (opzionale)


|===

NOTE: Su Kubernetes versione 1.20 e successive, utilizzare il validato `k8s.gcr.io/sig-storage/csi-snapshotter:v5.x` immagine solo se `v1` la versione di sta servendo `volumesnapshots.snapshot.storage.k8s.io` CRD. Se il `v1beta1` La versione sta servendo il CRD con/senza `v1` versione, utilizzare il validato `k8s.gcr.io/sig-storage/csi-snapshotter:v3.x` immagine.
